main:
  - name: 'Home'
    url: '/'
    weight: 1

  - name: 'Services'
    url: '/services/'
    weight: 2

  - name: 'Customers'
    url: '/customers/'
    weight: 3

  - name: 'About'
    url: '/#highlights'
    weight: 4

buttons:
  - name: 'Contact Us'
    url: '/#subscribe'
    weight: 6

footer:
  - name: 'Home'
    url: '/'
    weight: 1

  - name: 'Services'
    url: '/services/'
    weight: 2

  - name: 'Customers'
    url: '/customers/'
    weight: 3

  - name: 'About'
    url: '/#highlights'
    weight: 4

  - name: 'Contact'
    url: '/#subscribe'
